### ISSUE TITLE
Quest enumeration at site

### ISSUE THREAD

**Issue by RomanBelkov** [DiscoDancer/Quests#2]
Quest enumeration at site begins from 2, not 1
![bug](https://cloud.githubusercontent.com/assets/5811999/7094812/8a772978-dfcd-11e4-989e-a8c3beeda523.PNG)

**Comment by DiscoDancer** [comment]
База данных сама выдает id, id с номером 1 уже был. Ну тут как в контаче, даже если чувак с id 1 удалит свою страницу, новый пользователь никак не получит этот id.
